### ISSUE TITLE
[ros_comm/rosgraph] test_roslogging failed

### ISSUE THREAD

**Issue by kejxu** [ms-iot/ROSOnWindows#24]
```
2018-10-18T22:16:29.5637116Z ======================================================================
2018-10-18T22:16:29.5637213Z ERROR: test.test_roslogging.test_rosconsole__logging_format
2018-10-18T22:16:29.5637291Z ----------------------------------------------------------------------
2018-10-18T22:16:29.5637389Z Traceback (most recent call last):
2018-10-18T22:16:29.5637448Z   File "C:\opt\python27amd64\lib\site-packages\nose\case.py", line 197, in runTest
2018-10-18T22:16:29.5637489Z     self.test(*self.arg)
2018-10-18T22:16:29.5637535Z   File "D:\a\1\a\_ws\src\ros_comm\tools\rosgraph\test\test_roslogging.py", line 118, in test_rosconsole__logging_format
2018-10-18T22:16:29.5637756Z     assert_regexp_matches(lout.getvalue().splitlines()[i], log_out)
2018-10-18T22:16:29.5637819Z   File "C:\opt\python27amd64\lib\unittest\case.py", line 999, in assertRegexpMatches
2018-10-18T22:16:29.5637861Z     expected_regexp = re.compile(expected_regexp)
2018-10-18T22:16:29.5637980Z   File "C:\opt\python27amd64\lib\re.py", line 194, in compile
2018-10-18T22:16:29.5638035Z     return _compile(pattern, flags)
2018-10-18T22:16:29.5638076Z   File "C:\opt\python27amd64\lib\re.py", line 251, in _compile
2018-10-18T22:16:29.5638126Z     raise error, v # invalid expression
2018-10-18T22:16:29.5638180Z error: bogus escape: '\\1'
```

**Comment by kejxu** [comment]
fixed in https://github.com/ms-iot/ros_comm/pull/34
