### ISSUE TITLE
Can't use rosbag fix in melodic on Windows

### ISSUE THREAD

**Issue by void32** [ms-iot/ROSOnWindows#299]
**Describe the bug**
Can't use rosbag fix in melodic on Windows.

**To Reproduce**
1. Reindex bag
D:\rosbags\2020-10-22\71ca1737-23cf-4909-ae51-fe819c46e351>rosbag reindex 71ca1737-23cf-4909-ae51-fe819c46e351_2019-03-22-15-18-33_14.bag.active

2. Repair bag:
D:\rosbags\2020-10-22\71ca1737-23cf-4909-ae51-fe819c46e351>rosbag fix 71ca1737-23cf-4909-ae51-fe819c46e351_2019-03-22-15-18-33_14.bag.active 71ca1737-23cf-4909-ae51-fe819c46e351_2019-03-22-15-18-33_14.bag
Traceback (most recent call last):
  File "C:\opt\ros\melodic\x64\bin\rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "C:\opt\ros\melodic\x64\lib\site-packages\rosbag\rosbag_main.py", line 1012, in rosbagmain
    cmds[cmd](argv[2:])
  File "C:\opt\ros\melodic\x64\lib\site-packages\rosbag\rosbag_main.py", line 440, in fix_cmd
    migrator = MessageMigrator(rules, plugins=not options.noplugins)
  File "C:\opt\ros\melodic\x64\lib\site-packages\rosbag\migration.py", line 557, in __init__
    exec(open(pkg_dir + "/" + r).read(), scratch_locals)
IOError: [Errno 2] No such file or directory: 'C:\\opt\\ros\\melodic\\x64\\share\\joy/migration_rules/Joy.bmr'

**Expected behavior**

**Environment information:**
Microsoft Windows
Version 2004 (OS build 20175.1000)

Chocolatey v0.10.15
assimp 4.0.1.1809242322
boost 1.66.0.1904102339
bullet3 2.87.0.1809242326
bzip2 1.0.6.1901242108
chocolatey-core.extension 1.3.5.1
chocolatey-windowsupdate.extension 1.0.4
console_bridge 0.4.0.1809242322
cppunit 1.12.1.1809242322
cppzmq 4.2.2.1811162207
dlfcn-win32 1.1.1.1811162226
eigen 3.3.4.1809242322
freeimage 3.17.0.1811160037
gazebo9 9.4.1.1909060324
google-mock 1.8.0.1809242326
google-test 1.8.0.1809242322
gtk2 2.22.1.1904131648
hg 5.3.1
ilmbase 2.2.1.1811210800
jasper 2.0.14.1811210919
jxrlib 1.1.0.1811210809
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
lcms 2.8.0.1811210903
libcurl 7.58.0.1809242322
libflann 1.9.1.1809090720
libgraphviz 2.41.0.1810022039
liblzma 5.2.4.1811210837
libogg 1.3.3.1809090720
libopencv 3.4.1.1809242322
libpcl 1.8.1.1809090720
libpng 1.6.35.1809242322
libraw 0.19.0.1811210804
libtbb-dev 2018.6.0.1812011750
libtheora 1.1.1.1809090720
libwebp 0.6.1.1811210731
log4cxx 0.10.0.1809242322
lz4 1.8.1.1809242322
ogre 1.10.11.1901312214
openexr 2.2.1.1811210832
openjpeg 2.3.0.1811210736
openssl 1.1.1.1809242322
pkg-config 0.29.2.1809242322
poco 1.8.1.1809242322
protobuf 3.6.1.1811130545
pyqt5 5.10.1.1809242322
pyside2 5.10.1.1809242322
qt5-sdk 5.10.1.1903182340
qwt 6.1.3.1811212304
ros-catkin-tools 0.0.1.1903221831
ros-melodic-desktop_full 20200221.1
ros-python2 2.7.15.1904300710
ros-vcpkg 2018.11.23.1906112226
sbcl 0.0.0.1809242326
sdl 1.2.15.1809242322
sdl_image 1.2.12.1809242322
sip 4.19.8.1809242322
tiff 4.0.9.1811210742
tinyxml 2.6.2.1809242322
tinyxml2 6.1.0.1809242322
urdfdom 1.0.0.1809242322
urdfdom_headers 1.0.0.1809242322
vcpython27 9.0.30729.1809090720
vcredist140 14.25.28508.3
vcredist2010 10.0.40219.2
yaml-cpp 0.6.2.1901170034
zeromq 4.2.5.1811162203
zlib 1.2.11.1809242322
70 packages installed

**Comment by void32** [comment]
Reported twice: https://github.com/ms-iot/ROSOnWindows/issues/298
