### ISSUE TITLE
roslaunch error shutting down moveit: killpg not implemented on Windows

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#62]
roslaunch uses a unix method when shutting down, which causes an error.

```
[roslaunch][ERROR] 2019-01-20 19:16:21,368: [move_group-3] EXCEPTION Traceback (most recent call last):
  File "C:\opt\ros\melodic\x64\lib\site-packages\roslaunch\nodeprocess.py", line 534, in stop
    self._stop_win32(errors)
  File "C:\opt\ros\melodic\x64\lib\site-packages\roslaunch\nodeprocess.py", line 486, in _stop_win32
    os.killpg(pid, signal.SIGTERM)
AttributeError: 'module' object has no attribute 'killpg'
```

**Comment by seanyen** [comment]
This is fixed by the referenced pull request. I close it now.
